name: Draft release notes and update version

on:
  push:
    branches:
      - main

jobs:
  update_release_draft_and_version:
    permissions:
      contents: write # to create a release draft and a commit with the version number
    runs-on: ubuntu-latest
    steps:
      - name: Draft a new release
        id: draft_release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Update package version
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.draft_release.outputs.tag_name }}
          git-tag-version: 'false'

      - name: Commit version number update if changed
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Set version to match next release draft
