name: Testing

on:
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v5

      - name: Install dependencies
        run: yarn install

      - name: Run tests
        run: yarn test
